### ISSUE TITLE
Error on install for displayPaymentReturn hook

### ISSUE THREAD

**Issue by willem-v-dam** [paynl/prestashop-plugin#55]
On installing on PrestaShop 8.1.3 I get the following error

Kan actie Install niet toepassen op paynlpaymentmethods. Hook with the name displayPaymentReturn has been registered by PaynlPaymentMethods, but the corresponding method hookDisplayPaymentReturn has not been defined in the Module class.

The hook is registered, but there is no function to actually do something with the hook

**Comment by woutse** [comment]
Thanks your message. Fixed in 4.17.1!
