### ISSUE TITLE
View test order will result in render exception when no transaction

### ISSUE THREAD

**Issue by willem-v-dam** [paynl/prestashop-plugin#56]
When viewing a test order we get an exception that the variable "$amoutRefunded" does not exist. This is true, because in the method hookDisplayAdminOrder there is a try catch which fails.

The try catch tries to receive the payment on line 243, $this->getTransaction. This fails because the transaction does not exist. Im viewing an older order in the webshop which is not been payed using this module, therefore the $transactionId value is "Unavailable" and this transaction does not exist

**Comment by woutse** [comment]
Thanks, we'll took a look!

**Comment by woutse** [comment]
Again, thanks your message. Issue is fixed in release 4.17.1!
