### ISSUE TITLE
No refund when order slip is created via webservice

### ISSUE THREAD

**Issue by arisschl** [paynl/prestashop-plugin#58]
No refund is created at PAY when an order slip is created via the webservice API.

The refund is triggered by the hook `ActionOrderSlipAdd`, which is only called when the order slip is created via the PrestaShop back-office user interface.

Is it possible to add support for automatic refunding for order slips created via the webservice API?

**Comment by woutse** [comment]
Thanks for your message. Unfortunately, we searched, but couldn't find way to do this.
